// 질문·AL 예시답변 단일 원본. index.html, mock-exam.html, question-guide.html이 모두 이 파일을 읽습니다.
const QUESTIONS = [
 {
  "id": "q1",
  "source": "original",
  "topic": "자기소개",
  "type": "자기소개와 인사",
  "title": "자기소개",
  "q": "Tell me about yourself in detail. Let's start the interview now.",
  "flow": "인사 → 이름·나이·거주지·가족 → 직업과 성격 → 취미(음악·카페·공원·캠핑) → 마무리 인사",
  "tip": "자기소개는 채점 비중이 낮다고 알려져 있으니 1분 내외로 짧게 하세요. 뒤에 나올 주제(공원·캠핑·음악)를 미리 깔아 두면 답변 전체에 일관성이 생기고, 'to be honest', 'Anyway' 같은 연결어로 외운 티를 줄이세요.",
  "a": "Hi, nice to meet you. My name is Harry, and I'm in my mid-thirties. I live in Suwon, a city just south of Seoul, with my wife. I've been working at an IT company for about eight years, and to be honest, my job keeps me pretty busy, so I really value my free time. I'd describe myself as a bit of a homebody. On weekends, I like to relax at home, listen to music, or grab a coffee at a cafe near my place. When the weather is nice, my wife and I often take a walk around Gwanggyo Lake Park, which is only ten minutes from our apartment. We also go camping a few times a year, because it's a great way to get away from the busy city. Anyway, I'm a little nervous right now, but I'm excited to talk with you today. I hope we have a good conversation."
 },
 {
  "id": "q2",
  "source": "original",
  "topic": "집에서의 휴가",
  "type": "습관·일상",
  "title": "휴가 때 만나는 사람과 활동",
  "q": "When you spend your vacation at home, who usually visits you? What do you do together? Provide as many details as possible.",
  "flow": "방문자는 많지 않음 → 친구 민수(관계·함께 하는 일) → 부모님(명절·요리·대화) → 편안함이 좋은 이유",
  "tip": "'누가 오는지'를 묻는 질문이므로 인물 → 함께하는 활동 순서로 답하세요. 'We've known each other since…'(현재완료), 'end up -ing', 'once in a while' 같은 표현이 문단을 풍부하게 만듭니다.",
  "a": "Well, when I spend my vacation at home, I don't usually have a lot of visitors, but there are a couple of people who come over pretty regularly. The first one is my best friend, Minsu. We've known each other since high school, and he lives just a few subway stops away, so whenever we both have some time off, he drops by. Usually, we order some fried chicken, play video games, and just catch up on what's been going on in our lives. Sometimes we end up talking until two or three in the morning. My parents also visit once in a while, especially during long holidays like Chuseok. When they come, my wife and I cook a big meal together, and after dinner, we usually sit in the living room, drink some tea, and talk for hours. Honestly, these visits aren't anything fancy, but I think that's exactly why I enjoy them. I don't have to dress up or plan anything, and I can just relax with people I'm really comfortable with."
 },
 {
  "id": "q3",
  "source": "original",
  "topic": "집에서의 휴가",
  "type": "습관·선호",
  "title": "집에서 휴가를 보내는 이유와 방식",
  "q": "In your background survey, you indicated that you prefer to stay at home during vacations. How do you spend your vacations at home? What do you usually do? Give me as many details as possible.",
  "flow": "집 휴가를 선호하는 이유(내향적·여행의 비용과 피로) → 늦잠·브런치 → 드라마 몰아보기·산책 → 미뤄둔 정리 → 재충전",
  "tip": "선호 이유(why) → 하루 일과(how) → 느낌 순서로 답하세요. 'by the time…', 'things I keep putting off' 같은 복문과 'sleep in', 'binge-watch' 같은 구어 동사로 어휘 다양성을 보여주세요.",
  "a": "I prefer staying at home during my vacations, mainly because I'm kind of an introvert. Traveling can be fun, of course, but it takes a lot of planning, money, and energy, and by the time I come back, I often feel even more tired than before. So for me, a staycation is the best way to recharge. A typical vacation day at home goes like this. I sleep in without setting an alarm, and then I make myself a nice brunch, like pancakes or French toast. In the afternoon, I usually binge-watch a TV series that I've been saving for my time off. If the weather is nice, I take a walk around the lake park near my apartment. I also use my vacation to do things I keep putting off during the week, like cleaning out my closet or organizing my desk. It might sound boring to some people, but I really love it. By the end of the vacation, I feel completely refreshed and ready to go back to work."
 },
 {
  "id": "q4",
  "source": "original",
  "topic": "집에서의 휴가",
  "type": "과거 경험",
  "title": "지난 집 휴가의 하루",
  "q": "Specifically discuss the things that you did while on the last vacation that you spent at home. Give me a detailed description of what you did from the beginning to the end of the day, all of the activities you participated in, and all of the people you saw that day.",
  "flow": "추석 연휴 → 늦잠·아침 → 청소 → 친구 방문·파스타 요리 → 영화·보드게임 → 마무리 소감",
  "tip": "'처음부터 끝까지'를 요구하므로 시간 표현(At first, around two, After dinner, until midnight)으로 하루를 끝까지 이어가세요. 과거시제를 일관되게 유지하고, 작은 에피소드(마늘을 너무 많이 넣음)를 넣으면 이야기가 살아납니다.",
  "a": "My last vacation at home was during Chuseok a few weeks ago, and I remember that day pretty clearly. I woke up around ten, which felt amazing, because I usually get up at six-thirty for work. My wife and I had a late breakfast together, just some toast and coffee, and then we cleaned the apartment, because my best friend, Minsu, was coming over in the afternoon. He showed up around two with a bag of snacks. At first, we were planning to just chill out and watch a movie, but we got hungry, so we decided to cook pasta together. Honestly, it was a bit of a mess. Minsu added way too much garlic, but it actually turned out pretty good. After dinner, the three of us watched a thriller with the lights off, and then we played board games until almost midnight. After Minsu left, I washed the dishes and went straight to bed. Nothing special happened, but it was one of the most relaxing days I've had in a long time."
 },
 {
  "id": "q5",
  "source": "original",
  "topic": "은행",
  "type": "장소 묘사",
  "title": "우리나라 은행의 모습과 위치",
  "q": "Tell me about the banks in your country. What do they typically look like? Where are they usually located?",
  "flow": "위치(역 근처·번화가) → 내부 구조(ATM·번호표·창구) → 영업시간 → 모바일 뱅킹과 내 의견",
  "tip": "묘사형은 '밖 → 안 → 이용 방법 → 내 의견' 순서로 공간을 이동하며 설명하세요. 'which is…' 관계절과 'For example' 예시, 마지막 개인 의견이 단순 나열을 넘어서게 해 줍니다.",
  "a": "Banks in Korea are pretty easy to find, especially in big cities. They're usually located in busy areas, like near subway stations, in downtown business districts, or on the first floor of office buildings. In my neighborhood, for example, there are three or four different banks within a five-minute walk. Most of them look modern and clean. When you walk in, the first thing you see is an ATM area near the entrance, which is usually open even after the bank closes. Inside, there's a ticket machine where you take a number, and then you wait on the sofas until your number is called. The tellers sit behind long counters, and there's usually a separate section for loans and other bigger services. Banks here are typically open from nine to four on weekdays, which is honestly a little inconvenient for office workers like me. That's why these days, a lot of people, including me, mostly use mobile banking and only visit a branch when it's really necessary."
 },
 {
  "id": "q6",
  "source": "original",
  "topic": "은행",
  "type": "과거·현재 비교",
  "title": "어릴 때와 지금 은행의 차이",
  "q": "Banks have definitely changed over time. Tell me about a bank you remember from your childhood. What was the bank like? How was it different from banks today?",
  "flow": "어릴 때 엄마와 세뱃돈 저금 → 붐빔·종이 서식·통장 → 지금은 앱으로 대부분 처리 → 장단점 의견",
  "tip": "비교형 핵심: 'used to / would'로 과거 습관, 'Nowadays'로 현재 전환, 마지막에 장단점 평가. 기억을 묘사할 때 'I still remember that…'을 쓰면 자연스럽습니다.",
  "a": "Banks have definitely changed a lot since I was a kid. When I was in elementary school, my mom used to take me to the bank to put my New Year's money into my savings account. I still remember that the bank always felt crowded and noisy. People stood in long lines, and my mom had to fill out paper forms for everything, so the whole process took forever. I also had a small bankbook, and the teller would print each deposit in it, which I thought was really cool. Nowadays, things are completely different. I can open an account, send money, or even apply for a loan on my phone in just a few minutes. Bank branches are much quieter too, since most people don't need to visit them anymore. In fact, a lot of branches near my house have closed down. Some people say banks have lost their personal touch, and I kind of agree, especially for older people who aren't comfortable with apps. But overall, I think banking has become much faster and more convenient."
 },
 {
  "id": "q7",
  "source": "original",
  "topic": "은행",
  "type": "문제 해결 경험",
  "title": "은행에서 생긴 문제",
  "q": "Sometimes problems arise when dealing with the bank. Tell me in detail about a problem you had that involved your bank. Maybe the bank was closed when you needed it to be open. Maybe the bank made some kind of mistake. Tell me the story of a time when you had to solve a problem involving your bank.",
  "flow": "배경(앱 오류로 점심시간 방문) → 30분 대기 후 신분증 없음 발견 → 회사 왕복 → 두 번째엔 빠르게 해결 → 교훈",
  "tip": "문제 경험형은 '배경 → 문제 발생 → 해결 과정 → 결과·교훈' 구조입니다. 'That's when I realized…', 'I had no choice but to…', 'By that time…' 같은 전환 표현이 AL 서사의 핵심입니다.",
  "a": "I remember one really frustrating experience at the bank a couple of years ago. I needed to change the phone number linked to my account, but the app kept giving me an error, so I decided to visit a branch during my lunch break. I left the office in a hurry and waited in line for almost thirty minutes. When it was finally my turn, the teller asked for my ID, and that's when I realized I had left my wallet on my desk. I couldn't believe it. The teller was really nice about it, but she said she couldn't help me without an ID. So I had no choice but to run back to the office, grab my wallet, and come back. By that time, my lunch break was almost over, and I didn't even have time to eat. Luckily, the line was much shorter the second time, so everything was done in about five minutes. Since then, I always double-check that I have my ID before I go to a bank, and I try to go early in the morning instead of at lunchtime."
 },
 {
  "id": "q8",
  "source": "original",
  "topic": "음악",
  "type": "취향·이유",
  "title": "좋아하는 음악과 음악가",
  "q": "You indicated in the survey that you listen to music. What kinds of music do you listen to? Who are some of your favorite musicians or composers?",
  "flow": "여러 장르, 요즘은 K-pop → 뉴진스를 좋아하는 이유(차분함·레트로) → 뮤직비디오·안무 → 브루노 마스 → 취향 정리",
  "tip": "취향 질문은 '대상 → 좋아하는 이유 2~3개 → 비교 → 정리' 순서로 답하세요. 'What I like about them is that…'(강조 구문)과 'even though…' 양보절로 이유를 깊이 있게 설명하세요.",
  "a": "I listen to all kinds of music, but these days I'm really into K-pop, and my favorite group is definitely NewJeans. What I like about them is that their music sounds different from typical K-pop. A lot of K-pop songs are really loud and intense, but their songs are more relaxed and kind of retro, almost like nineties R&B. So I can listen to them over and over without getting tired. Their music videos are also really creative, and their choreography looks effortless, even though I know it must be really hard. Besides K-pop, I also enjoy pop music, especially Bruno Mars. My dad introduced me to his songs when I was a teenager, and I still listen to his albums when I'm driving. His voice is just amazing, and his songs always put me in a good mood. So basically, I'd say I like music that's catchy but not too heavy. If you haven't heard NewJeans yet, I'd definitely recommend checking them out."
 },
 {
  "id": "q9",
  "source": "original",
  "topic": "음악",
  "type": "취향 변화",
  "title": "음악 취향의 변화",
  "q": "When did you first become interested in music? What kinds of music did you like first? Tell me how your interest in music developed from your childhood until today.",
  "flow": "10살 아빠 차 안에서 팝 → 중학생 MP3·록 → 대학 시절 힙합 → 현재 K-pop·R&B → 취향과 성격의 변화",
  "tip": "변화를 말할 때는 시기 표현(When I was…, In college, These days)으로 3단계 이상 나누세요. 'went through a … phase', 'got me into…', 'Looking back,…'은 AL 수준의 연결 표현입니다.",
  "a": "I think I first got interested in music when I was around ten. My dad loved pop music, so he always played CDs in the car, and that's how I got to know artists like Michael Jackson and, later, Bruno Mars. Back then, I didn't understand the lyrics at all, but I loved singing along anyway. When I was in middle school, I got my first MP3 player, and that totally changed things. I started finding music on my own, and I went through a rock phase. I listened to bands like Linkin Park almost every day, probably because I was a moody teenager. In college, my friends got me into hip-hop, and I even tried writing some lyrics, though they were pretty terrible. These days, my taste has become a lot more relaxed. I mostly listen to K-pop and calm R&B, especially while I'm commuting or working. Looking back, I think my taste in music changed along with my personality, and that's what makes it kind of fun to think about."
 },
 {
  "id": "q10",
  "source": "original",
  "topic": "음악",
  "type": "과거 경험",
  "title": "기억에 남는 라이브 음악",
  "q": "Could you think back to a particularly memorable time when you heard live music? Describe that experience in detail. When was it? Where were you? Who were you with? Who did you hear? What happened that made that performance so memorable?",
  "flow": "언제·어디·누구(2년 전 도쿄) → 입장 전 분위기 → 좌석과 공연 → 최고의 순간(떼창) → 여운",
  "tip": "경험 질문은 5W(언제·어디·누구·무엇·왜)를 앞에서 빠르게 처리하고 '가장 기억에 남는 순간'에 시간을 쓰세요. 'I'd never experienced anything like that before.'(과거완료)와 감각 묘사가 답변을 한 단계 끌어올립니다.",
  "a": "The most memorable live music experience I've ever had was a NewJeans concert in Tokyo about two years ago. My friend and I are both big fans, and we were lucky enough to get tickets, so we booked a flight right away. The concert was at the Tokyo Dome, and when we got there, the line to get in was already huge. Everyone was wearing matching T-shirts and holding light sticks, so the atmosphere was incredible even before the show started. Our seats weren't very close to the stage, but there were huge screens, so we could see everything. The best moment was when they performed my favorite song and the whole stadium started singing along in Korean. It was so loud that I could feel it in my chest, and honestly, it gave me goosebumps. I'd never experienced anything like that before. On the way back to the hotel, my friend and I couldn't stop talking about it. Even now, whenever I hear that song, it takes me right back to that night."
 },
 {
  "id": "q11",
  "source": "original",
  "topic": "해외여행",
  "type": "장소 묘사",
  "title": "방문한 나라의 풍경과 사람",
  "q": "Can you describe for me one of the countries or cities you visited? What does it look like, and what are the people like there?",
  "flow": "오사카 선택 → 거리·도톤보리 묘사 → 근교 자연·사찰 → 사람들(친절함·도쿄와 비교) → 재방문 의사",
  "tip": "도시 묘사는 '전체 인상 → 대표 장소 → 사람' 순서로, 질문 순서를 그대로 따라가세요. 'As for the people,…'로 화제를 전환하고 'known for being…', 'a mix of A and B' 같은 묘사 표현을 활용하세요.",
  "a": "One of the countries I've visited is Japan, and I'd like to talk about Osaka, since I've been there twice. Osaka is a big, lively city, but it feels quite different from Seoul. The streets are really clean, and there are lots of narrow alleys full of small restaurants and shops. The most famous area is Dotonbori, where huge neon signs line both sides of a canal. At night, the whole area lights up, and it's always packed with tourists taking pictures. If you go a little outside the city, you can see mountains and old temples, so there's a nice mix of modern and traditional scenery. As for the people, they were really polite and helpful. Even though I don't speak Japanese, the staff at restaurants and stores were patient with me and tried to communicate with gestures. People in Osaka are also known for being friendlier and more talkative than people in Tokyo, and I could definitely feel that. Overall, it's a city I'd love to visit again, especially for the food."
 },
 {
  "id": "q12",
  "source": "original",
  "topic": "해외여행",
  "type": "선호·이유",
  "title": "좋아하는 여행지와 산·바다 선호",
  "q": "On your background survey, you indicated that you enjoy overseas travel. Where do you like to visit? Which do you prefer, mountains or beaches? Describe the place you like to visit and why you like to go there.",
  "flow": "해외여행 빈도 → 해변 선호, 다낭 소개 → 해변이 좋은 이유(휴식) → 산과 비교 → 결론",
  "tip": "선택 질문은 첫 문장에서 바로 선택(beaches)을 밝히고 이유 2개와 반대쪽과의 비교로 마무리하세요. 'That's why I always end up…'처럼 결론을 다시 묶어 주면 조직력이 드러납니다.",
  "a": "Honestly, I don't travel abroad that often, maybe once a year, but when I do, I definitely prefer beaches over mountains. My favorite place so far is Da Nang in Vietnam. It's only about a five-hour flight from Korea, and it has a long, beautiful beach with soft white sand. The hotels there are pretty affordable too, so you can stay at a nice resort without spending too much money. The reason I like beaches is pretty simple. When I go on vacation, I want to rest, not hike up a mountain and get exhausted. At the beach, I can just lie on a sunbed, read a book, and jump into the water whenever I get hot. In the evening, I love having a cold drink while watching the sunset. Mountains are beautiful too, of course, and I go hiking in Korea sometimes, but there are mountains everywhere here. So when I travel overseas, I want something totally different. That's why I always end up choosing a place by the sea."
 },
 {
  "id": "q13",
  "source": "original",
  "topic": "해외여행",
  "type": "과거 경험",
  "title": "가장 기억에 남는 여행",
  "q": "What is the most memorable experience you have had while traveling? When and where did you go? What happened? Why was it memorable? Describe the experience in detail.",
  "flow": "2년 전 친구와 오사카 → 교토에 가려다 역에서 길을 잃음 → 할머니가 매표소까지 안내 → 감사 → 특별한 도시가 된 이유",
  "tip": "이야기는 '배경 → 문제 → 전환점 → 결과 → 의미' 5단계로 구성하세요. 'The problem was that…', 'She didn't just…, she actually…' 같은 대비 구문이 이야기에 긴장감을 줍니다.",
  "a": "The most memorable travel experience I've had was about two years ago, when I went to Osaka with my best friend. On our second day, we were planning to visit Kyoto, so we went to a huge train station in Osaka. The problem was that the station was like a maze. There were so many lines and signs, and we had no idea which train to take. We kept walking around in circles for almost thirty minutes, and we were getting really stressed. Then an elderly Japanese lady came up to us and asked, in very simple English, where we were going. When we told her, she didn't just point us in the right direction. She actually walked us all the way to the ticket office and helped us buy the right tickets. We couldn't really communicate well, but we kept bowing and saying thank you. She just smiled and waved goodbye. It was such a small thing for her, but it meant a lot to us. Because of her kindness, Osaka has become a really special city to me."
 },
 {
  "id": "q14",
  "source": "original",
  "topic": "롤플레이",
  "type": "롤플레이·질문",
  "title": "해외 친구에게 지리에 관해 묻기",
  "q": "I'd like to give you a situation and ask you to act it out. You are going to meet your friend living overseas. Call your friend and ask two or three questions about geography.",
  "flow": "인사·방문 소식 → 지형 질문 → 호수·해변 질문 → 7월 날씨·옷차림 질문 → 추천 요청 → 마무리",
  "tip": "롤플레이 질문하기: 상황 설정 → 질문 3~4개(각 질문에 '왜 묻는지' 한 문장씩) → 마무리 인사. 'First of all / Second / And lastly'로 질문을 구분하면 체계적으로 들립니다.",
  "a": "Hey, Emma! It's me, Harry. How have you been? I have some exciting news. I'm finally coming to visit you in Canada this summer! I've already started planning, but since it's my first time there, I have a few questions about the geography, if you don't mind. First of all, what's the landscape like around your city? Is it mostly flat, or are there a lot of mountains? I'd love to do some hiking if there are good trails nearby. Second, are there any lakes or beaches close enough for a day trip? I've heard Canada has amazing lakes, and I really want to see one. And lastly, what's the weather usually like in July? I want to know whether I should pack only summer clothes or bring a jacket too, because I've heard it can get chilly at night in some areas. Oh, and if there's any place you think I absolutely shouldn't miss, please let me know. Anyway, I can't wait to see you. Let's talk more soon. Bye!"
 },
 {
  "id": "q15",
  "source": "original",
  "topic": "롤플레이",
  "type": "롤플레이·대안",
  "title": "해외 친구와 약속 취소 및 대안",
  "q": "I'm sorry, but there is a problem which I need you to resolve. You are unable to meet your friend who is living in another country. Call your friend and give three or four alternatives to address the problem.",
  "flow": "사과 → 이유(출장) → 대안 1 일정 연기 → 대안 2 친구를 한국에 초대 → 대안 3 중간 지점에서 만나기 → 취소 비용 부담 → 선택 요청",
  "tip": "문제 해결 롤플레이는 AL의 핵심 과제입니다. 이유를 구체적으로 설명하고, 대안 3개 이상과 각 대안의 근거(항공권이 더 쌈, 호텔비 부담)를 덧붙이세요. 'push back', 'meet halfway', 'make it happen' 같은 구어 표현이 효과적입니다.",
  "a": "Hey Emma, it's Harry again. I'm really sorry, but I have some bad news. I just found out that my company is sending me on a business trip the exact same week I was supposed to visit you. I tried to get out of it, but my manager said it's really important, so there's nothing I can do. I feel terrible, because I know you've already made plans for us. So I've been thinking about a few options. First, I could push my trip back to September. I checked the flights, and they're actually a bit cheaper then. Second, if September doesn't work for you, how about you come to Korea instead? I'd be happy to pay for your hotel and show you around Seoul. Third, if neither of those works, maybe we could meet halfway, like in Japan, during the winter holidays. And of course, I'll cover any cancellation fees if you've already booked anything for us. Again, I'm so sorry about this. Just let me know which option works best for you, and I'll make it happen."
 },
 {
  "id": "q16",
  "source": "original",
  "topic": "롤플레이",
  "type": "롤플레이·질문",
  "title": "친구에게 MP3 구매 정보 묻기",
  "q": "I'd like to give you a situation to act it out. You want to buy a new MP3 Player and your friend bought a new MP3 player recently. Ask three or four questions to your friend about a new MP3 Player you want to buy.",
  "flow": "인사·구매 이유 → 브랜드·가격 → 배터리 → 저장 용량 → 블루투스 → 단점 → 감사",
  "tip": "질문마다 '내 상황'을 붙이면(예: 한 시간 달리기 → 배터리) 단순한 질문 나열이 아니라 맥락 있는 대화가 됩니다. 'I'm wondering if…' 같은 간접 의문문도 섞어 보세요.",
  "a": "Hey, Jisoo! Do you have a minute? I heard you just bought a new MP3 player. Actually, I'm thinking about getting one too, because I want to listen to music while I'm running without carrying my phone. So I wanted to ask you a few questions before I buy one. First, which brand did you get, and how much did it cost? I'm trying not to spend more than a hundred dollars. Second, how long does the battery last? I usually run for about an hour, and I don't want it to die in the middle of my workout. Third, how much storage does it have? I have a lot of songs, so I need enough space for at least a few thousand of them. Also, I'm wondering if it supports Bluetooth. I use wireless earphones, so that's really important to me. And lastly, are there any downsides you've noticed so far? Anyway, thanks a lot. If you really like it, maybe I'll just get the same one."
 },
 {
  "id": "q17",
  "source": "original",
  "topic": "롤플레이",
  "type": "롤플레이·대안",
  "title": "빌린 MP3를 고장낸 뒤 해결하기",
  "q": "I'm sorry, but there is a problem I need to resolve. You have borrowed your friend's mp3 player but broke it by accident. Call your friend and explain the situation. Give 2-3 alternatives that will help solve the situation.",
  "flow": "망설임·사과 → 고장 경위(달리기 중 떨어뜨림) → 상태 설명 → 대안 1 수리비 부담 → 대안 2 새 제품 → 대안 3 현금 → 결정 요청",
  "tip": "사고 경위를 과거진행형(while I was tying my shoes)으로 생생하게 설명한 뒤 대안을 제시하세요. 'You know the … you lent me?'로 상대의 기억을 떠올리게 하는 시작은 원어민스러운 롤플레이 표현입니다.",
  "a": "Hey, Jisoo, it's me. Um, I have something to tell you, and I feel really bad about it. You know the MP3 player you lent me last week? I took it with me when I went running yesterday, and while I was tying my shoes, it slipped out of my pocket and fell onto the concrete. I picked it up right away, but the screen was completely cracked, and now it won't even turn on. I'm so, so sorry. I know you just bought it. So here's what I'm thinking. First, I already looked up a repair shop nearby, so I can take it there tomorrow and pay for the repair myself. Second, if it can't be fixed or the repair takes too long, I'll just buy you a brand-new one, the exact same model. Or, if you'd prefer, I could give you the money, and you could pick out a newer model you like better. It's totally up to you. Again, I'm really sorry. Let me know what you want me to do, and I'll take care of it as soon as possible."
 },
 {
  "id": "q18",
  "source": "original",
  "topic": "지리",
  "type": "지형 묘사",
  "title": "우리나라 지형과 자연환경",
  "q": "Describe the geography in your country. Are there mountains there? Is the seashore part of the geography? Are there lakes? Discuss all the details you can about the geography and landscape in your country.",
  "flow": "반도·국토의 70%가 산지 → 동쪽은 높고 서쪽은 낮은 지형 → 동해·서해·남해의 특징 → 호수(인공호) → 다양성에 대한 의견",
  "tip": "사실 정보는 정확하게 말하세요(반도, 국토의 약 70%가 산지). 'while…'로 동서를 대조하고, 'each one has its own character'로 분류한 뒤 하나씩 설명하는 구조가 조직력 평가에 좋습니다.",
  "a": "Korea is a peninsula, so it's surrounded by the sea on three sides, and about seventy percent of the land is covered with mountains. Because of that, you can see mountains almost everywhere, even in the middle of Seoul. The eastern part of the country has higher and steeper mountains, like Seoraksan, while the western side is flatter, which is why most of the big cities and farmland are there. As for the seas, each one has its own character. The East Sea is deep and clear, with beautiful sandy beaches. The West Sea is shallow and famous for its huge tidal flats, where you can see mud for miles when the tide goes out. The South Sea has thousands of small islands, and Jeju Island, the most popular vacation spot in Korea, is off the south coast. We don't have many big natural lakes, but there are a lot of man-made lakes created by dams on the rivers. Personally, I think this variety is one of the best things about Korea. Within just a few hours, you can go from the mountains to the beach."
 },
 {
  "id": "q19",
  "source": "original",
  "topic": "캠핑",
  "type": "습관·일상",
  "title": "캠핑 빈도·계절·동행·활동",
  "q": "In your background survey, you indicated that you like going camping. How often do you go camping, and what time of the year do you typically go? Who do you usually go with? What do you like to go on camping trips?",
  "flow": "빈도 → 가을을 선호하는 이유(계절 비교) → 동행·장소 → 좋아하는 이유(화면에서 벗어남·모닥불) → 재충전",
  "tip": "네 가지 질문(빈도·계절·동행·좋아하는 점)에 빠짐없이, 순서대로 답하세요. 계절 비교로 이유를 대고 'What I like most about … is that…'으로 핵심을 강조하면 체계적으로 들립니다.",
  "a": "I go camping about three or four times a year, and my favorite season for camping is definitely fall. In summer, it's way too hot and there are tons of mosquitoes, and in winter, it's just too cold for me, even with a good sleeping bag. But in October, the weather is cool and dry, and the leaves are changing color, so it's perfect. I usually go with my wife, and once or twice a year, we go with a couple of close friends. We usually pick a campsite in Gangwon-do or Gapyeong, because they're only a couple of hours' drive from where we live. What I like most about camping is that it gives me a break from screens. During the week, I stare at a computer all day, but at the campsite, I just set up the tent, cook outside, and sit around the campfire talking for hours. Grilling meat outdoors also makes it taste ten times better, or at least that's how it feels. When I come back home, I always feel recharged."
 },
 {
  "id": "q20",
  "source": "original",
  "topic": "캠핑",
  "type": "과거 경험",
  "title": "최근 캠핑의 상세한 경험",
  "q": "When was the last time you went camping? Where did you go? Who did you go with? Describe what you did on your camping trip in as much detail as you can.",
  "flow": "지난 8월·강원도·아내와 친구 부부 → 교통 체증 → 텐트와 점심 분담 → 계곡 → 바비큐·모닥불 → 아침 산책 → 귀가와 소감",
  "tip": "기존 답변의 어색한 문장('As for the result', 'walked for I felt')을 고쳤습니다. 과거 경험은 시간 순서에 'By the time we arrived', 'so … that…' 구조를 더해 연결하고, 일정을 끝까지 마무리하세요.",
  "a": "The last time I went camping was this past August. My wife and I went to a campsite next to a river in Gangwon-do with two of our friends. We left early in the morning to avoid traffic, but there was an accident on the highway, so it took almost four hours to get there. By the time we arrived, we were starving, so we split up the work. My friend and I set up the tents, while my wife and his wife started a fire and made some ramen for a quick lunch. In the afternoon, we went down to the river, and the water was so cold that we could only stay in for a few minutes. In the evening, we had a big barbecue. We grilled pork belly and sausages, and later we roasted marshmallows over the campfire and talked until really late. The next morning, we woke up early and took a walk along the river. It was so quiet and peaceful that I felt like I was really far away from the city. We packed up around noon and headed home. It was tiring, but it was totally worth it."
 },
 {
  "id": "q21",
  "source": "original",
  "topic": "캠핑",
  "type": "사물·기능 묘사",
  "title": "최근 캠핑 장비와 기능",
  "q": "These days, camping is very popular. What are the recent gears? What are their special features?",
  "flow": "캠핑 인기 → 휴대용 파워뱅크(기능·과거와 비교) → 원터치 텐트(내 경험) → 소형 버너 → 의견",
  "tip": "사물 묘사는 '무엇인지 → 어떻게 쓰는지 → 예전과 비교 → 내 의견' 순서로 하세요. 'It's basically…'로 쉽게 정의하고 'Back in the day'로 과거와 대비하면 설명력이 올라갑니다.",
  "a": "Camping has become really popular in Korea over the last few years, and because of that, camping gear has improved a lot. One item a lot of people use these days is the portable power station. It's basically a big rechargeable battery about the size of a lunch box. You can charge your phone, run an electric blanket, or even use a small coffee machine with it. Back in the day, you needed a campsite with an electric hookup to do any of that, but now you can camp almost anywhere. Another popular item is the one-touch tent. You just take it out of the bag, pull a couple of strings, and it pops up in less than a minute. When I first started camping, setting up a tent took my friends and me almost an hour, and we always ended up arguing. Lastly, a lot of campers use compact gas stoves that can also work as a grill. They're light and don't take up much space. Honestly, camping gear these days is so convenient that it almost feels like you're bringing your home into the woods."
 },
 {
  "id": "q22",
  "source": "original",
  "topic": "캠핑",
  "type": "의견·이슈",
  "title": "캠핑장의 환경 문제",
  "q": "A lot of people are worried that the camping site might have some environmental issues among campers. What do you say about this issue?",
  "flow": "공감 → 문제 1 쓰레기(직접 목격) → 문제 2 불법 화기 → 긍정적인 변화(흔적 남기지 않기·벌금) → 내 의견·해결책",
  "tip": "이슈형(13~15번 고난도 질문)은 AL 판정에 중요합니다. '문제 제기 → 구체 사례 → 반대 측면(On the other hand) → 내 의견(In my opinion)' 구조로, 개인 경험을 넘어 사회 전체의 관점에서 말하세요.",
  "a": "I think this is a really valid concern. As camping has become more popular, the number of campers has increased a lot, and unfortunately, not everyone treats nature with respect. The biggest problem is probably trash. Some people leave food waste, disposable plates, and even broken chairs behind, assuming someone else will clean up after them. I've actually seen piles of garbage next to a campsite in Gapyeong, and it was really disappointing. Another issue is campfires. When people make fires in places where it's not allowed, it can damage the ground or even cause a forest fire. On the other hand, I've noticed that more and more campers are becoming aware of these problems. Some of them follow the 'leave no trace' rule, which means you take everything you bring back home with you. Some campsites have also started fining people who don't clean up. In my opinion, though, rules alone aren't enough. Campers need to change their attitude. If we want to keep enjoying camping in the future, we all have to take responsibility for protecting nature."
 },
 {
  "id": "q23",
  "source": "original",
  "topic": "공원",
  "type": "장소 묘사",
  "title": "좋아하는 공원의 위치와 모습",
  "q": "In your background survey, you mentioned that you like going to parks. Please tell me about the park you like to go to. Where is it located, and what does it look like? What makes it special?",
  "flow": "광교호수공원·거리 → 규모(호수 두 개·산책로) → 풍경(나무·잔디·데크) → 특별한 점(야경) → 도시 속 휴식처",
  "tip": "기존 답변의 문법 오류(My wife and I favorite park, this is huge)를 고쳤습니다. 장소 묘사는 '위치 → 규모 → 구성 요소 → 특별한 점' 순서로 하고 'What makes it special is…'로 마무리하세요.",
  "a": "The park I like going to the most is Gwanggyo Lake Park in Suwon. It's only about a ten-minute drive from my apartment, so my wife and I go there almost every weekend. The park is really big. It actually has two lakes, and there's a walking path that goes all the way around them. It takes about an hour to walk the whole thing. Along the path, there are tall trees, flower beds, and plenty of benches where you can sit and look at the water. There's also a huge grassy area where families have picnics, and a wooden deck that goes out over the lake. What makes it special, in my opinion, is the night view. When the sun goes down, the lights around the lake and the bridges turn on, and the reflection on the water is really beautiful. Even though it's surrounded by tall apartment buildings, once you're inside the park, it feels like you're somewhere far away from the city. That's why it's my favorite place to relax."
 },
 {
  "id": "q24",
  "source": "original",
  "topic": "공원",
  "type": "습관 질문·경험 답변",
  "title": "공원에서 하는 평소 활동",
  "q": "What kind of activities do you usually do at the park? Do you take walks or exercise at the park? Do you prefer to go there with others, or do you prefer to go alone? Please describe a typical day at the park.",
  "flow": "주로 걷기(운동) → 아내와 함께 vs 혼자 → 오후 4시 출발 → 산책·벤치 → 피크닉 → 커피 → 회사 행사와 비교",
  "tip": "기존 답변은 '평소에 하는 일'을 묻는데 '한 번의 경험'으로 답했고 문법 오류도 많았습니다. 습관 질문은 현재시제와 빈도부사(usually, sometimes)로 답하고, 경험은 마지막에 짧게 덧붙이세요.",
  "a": "I usually go to the park on weekends, and it's mostly for walking. I sit at a desk all week, so walking around the lake for about an hour is basically my exercise. I prefer going with my wife, because we can talk about our week while we walk. But sometimes, when I need time to think, I go alone and listen to a podcast. A typical day at the park goes something like this. We usually head out in the late afternoon, around four, when it's not too hot. We walk around the lake first, and then we sit on a bench and just people-watch for a while. There are always kids flying kites and people walking their dogs, which is really fun to watch. If the weather's nice, we bring a blanket and some snacks and have a little picnic on the grass. Before going home, we usually grab a coffee at a cafe near the park. It's a simple routine, but it's one of my favorite parts of the week. Actually, my company held a team-building event at Hangang Park last month, and we played badminton there, but honestly, I enjoy quiet walks a lot more."
 },
 {
  "id": "q25",
  "source": "original",
  "topic": "커피숍",
  "type": "습관·일상",
  "title": "커피숍 방문 시기·주문·활동",
  "q": "In your background survey, you indicated that you like going out for coffee. When do you usually go to coffee shops? What do you typically order, and what do you do while you are there?",
  "flow": "방문 빈도 → 평일·주말 시간대 → 주문(아이스 아메리카노·바닐라 라떼) → 함께 가는 사람별 활동 → 단골 카페 → 카페의 의미",
  "tip": "'What I do depends on…'으로 상황을 나눠 답하면 길이와 구조를 동시에 확보할 수 있습니다. 'go-to drink', 'in the mood for', 'catch up' 같은 생활 구어 표현을 익혀 두세요.",
  "a": "I'm a big coffee person, so I go to coffee shops pretty often, probably four or five times a week. On weekdays, I usually grab a coffee on my way to work, and on weekends, I like to spend a few hours at a cafe in the afternoon. My go-to drink is an iced Americano. I drink it even in the middle of winter, which a lot of Koreans do, actually. But when I'm in the mood for something sweet, I'll order a vanilla latte with a piece of cake. What I do at the cafe depends on who I'm with. When I meet friends, we just chat and catch up for hours. When I go with my wife, we usually talk about our plans for the week. But if I'm alone, I bring my laptop or a book. There's a small cafe near my apartment with big windows and quiet music, and that's where I like to read. For me, cafes aren't just places to drink coffee. They're more like a space where I can take a break from my busy routine and recharge."
 },
 {
  "id": "q26",
  "source": "original",
  "topic": "커피숍",
  "type": "문제 경험",
  "title": "기억에 남는 커피숍 경험",
  "q": "Tell me about a memorable experience you have had at a coffee shop. When and where was it? Who were you with? What happened? Talk about the experience in detail, and explain why it was so memorable.",
  "flow": "몇 달 전 새로 생긴 카페 → 긴 줄 → 지갑과 휴대폰을 두고 옴 → 당황 → 집에 다녀옴 → 바리스타가 케이크를 남겨 둠 → 단골이 됨",
  "tip": "반전(To my surprise,…)이 있는 이야기는 기억에 남습니다. 감정 표현(I could feel my face turning red, I was really touched)을 구체적으로 넣고, 결말을 현재와 연결하세요.",
  "a": "One memorable experience at a coffee shop happened just a few months ago. A new cafe opened in my neighborhood, and it became really popular on social media because of its strawberry cake. So one Sunday afternoon, I decided to check it out by myself. When I got there, the line was out the door, and I waited for almost twenty minutes. Finally, when it was my turn, I ordered a latte and the famous cake, reached into my pocket, and realized I'd left my wallet and my phone at home. I was so embarrassed. There were a lot of people waiting behind me, and I could feel my face turning red. I apologized and told the staff I'd be right back. I ran home, which took about ten minutes, grabbed my wallet, and came back. To my surprise, the barista remembered me and said she'd saved the last piece of cake for me. I was really touched. The cake was honestly just okay, but that small act of kindness made it taste extra special. Since then, that cafe has become my favorite place in the neighborhood."
 },
 {
  "id": "q27",
  "source": "original",
  "topic": "집",
  "type": "장소 묘사",
  "title": "집과 좋아하는 방 묘사",
  "q": "Please tell me about your house. What’s your favorite room? What does it look like? Why do you like that room?",
  "flow": "집 소개 → 가장 좋아하는 방(서재) → 들어가면 보이는 배치(책상·책장·의자) → 벽 색 → 좋아하는 이유 → 하루 마무리",
  "tip": "방 묘사는 '들어가면 보이는 것 → 왼쪽/오른쪽' 순서로 공간을 이동하며 구체적으로 말하세요. 'which makes the room feel…' 관계절과 'The reason I love… is that…'으로 이유를 분명히 하세요.",
  "a": "I live in a three-bedroom apartment with my wife, and my favorite room is definitely our small study. It's the smallest room in the apartment, but it's where I spend most of my free time. When you walk in, the first thing you notice is a big wooden desk right in front of the window. During the day, a lot of sunlight comes in, so I don't even need to turn on the lights. On the left side, there's a tall bookshelf full of books and some camping magazines, and on the right, there's a comfortable reading chair with a small lamp next to it. We painted one wall a light sky blue, which makes the room feel calm and a little bigger than it actually is. The reason I love this room is that it's my own personal space. When I'm in there, I can read, listen to music, or just think without any distractions. Sometimes I even work from home in there. After a long day, sitting in that chair with a book is the best way for me to unwind."
 },
 {
  "id": "q28",
  "source": "original",
  "topic": "집",
  "type": "과거·현재 비교",
  "title": "예전 집과 현재 집 비교",
  "q": "Compare the home you lived in before to the one you live in now. What are the differences between those two homes? Provide me with as many details as possible.",
  "flow": "빌라 → 아파트 → 차이 1 보안 → 차이 2 편의시설 → 차이 3 주차 → 예전 집의 장점 → 결론",
  "tip": "비교는 'First of all / Second / Another big difference'로 항목마다 과거와 현재를 짝지어 말하세요. 'That said,…'로 반대 측면을 인정한 뒤 결론을 내리면 AL다운 균형 잡힌 답변이 됩니다.",
  "a": "Before I got married, I lived in a small villa for about five years, and now I live in an apartment with my wife. The two places are quite different. First of all, the security is way better now. My old building didn't have a security guard or even a lock on the front entrance, so anyone could walk in, and I sometimes felt a little uneasy at night. My current apartment complex has security guards, cameras everywhere, and a key-card system, so I feel much safer. Second, there are a lot more facilities. My complex has a gym, a small library, and even walking trails, which is super convenient. Back then, I had to pay for a gym membership somewhere else. Parking is another big difference. At the villa, there were only a few parking spots, so I often had to circle the neighborhood for twenty minutes. Now there's an underground parking lot, so that's not a problem anymore. That said, my old place had one big advantage. It was much cheaper, and my neighbors were really friendly. Overall, though, I'm much happier where I live now."
 },
 {
  "id": "q29",
  "source": "predicted",
  "topic": "집에서의 휴가",
  "type": "과거·현재 비교",
  "title": "예전과 지금의 휴가 비교",
  "q": "How have your vacations changed since you were a child? Compare what you did then with what you do now, and explain which you prefer.",
  "flow": "어릴 때 여름마다 가족 여행(would) → 설렘과 피로 → 지금은 집에서 휴식 → 선호와 이유 → 그리움 → 미래",
  "tip": "과거 습관은 'would + 동사', 현재는 현재시제, 미래 가정은 'Maybe when I have kids…'로 말하세요. 세 가지 시제를 자연스럽게 오가면 AL에 필요한 시제 통제력을 보여줄 수 있습니다.",
  "a": "My vacations have changed a lot since I was a kid. When I was young, my family went on a trip almost every summer. My dad would pack the car the night before, and we'd leave at five in the morning to avoid traffic. We usually went to the beach in Gangneung or to my grandparents' house in the countryside. I remember those trips being really exciting, but also exhausting, because we spent so many hours in the car. These days, I usually spend my vacations at home. I sleep in, cook something simple, watch movies, and take walks around the lake park near my apartment. I don't have to deal with traffic, crowded beaches, or expensive hotels. If you ask me which I prefer, I'd say I like my vacations now better, at least at this stage of my life. Work keeps me so busy that what I really need is rest, not adventure. But I have to admit, sometimes I miss those summer road trips with my family. Maybe when I have kids of my own, I'll start doing that again."
 },
 {
  "id": "q30",
  "source": "predicted",
  "topic": "집에서의 휴가",
  "type": "문제 경험",
  "title": "집에서 보내는 휴가 중 계획 변경",
  "q": "Tell me about a time when something unexpected happened during a vacation at home. What was your plan, what went wrong, and how did you handle it?",
  "flow": "영화 보는 하루 계획 → 인터넷 장애·통신사 연락 → 짜증 → 친구 방문 → 요리·대화 → 예상보다 즐거웠던 결말",
  "tip": "'I'd been looking forward to it'(과거완료진행), 'right when I was about to…', 'ended up -ing', 'turned out to be…'는 예상 밖의 상황을 말할 때 꼭 필요한 표현입니다.",
  "a": "Last winter, I planned to spend a whole day watching movies at home. I'd been looking forward to it for weeks. I made a list of movies, bought some snacks, and even made popcorn. But right when I was about to start the first movie, my internet suddenly stopped working. I restarted the router a couple of times, but nothing changed. When I called the internet company, they said there was an outage in my area and it might take several hours to fix. I was really annoyed, because my whole plan depended on the internet. While I was complaining about it, my friend Minsu texted me and asked what I was up to. When I told him what had happened, he said he'd come over. So we ended up cooking pasta together and just talking for hours without looking at our phones. We talked about old memories from high school and laughed a lot. By the time the internet came back, it was already late at night, and honestly, I didn't even care anymore. My movie plan didn't work out, but the day turned out to be way more fun than I expected."
 },
 {
  "id": "q31",
  "source": "predicted",
  "topic": "은행",
  "type": "습관·일상",
  "title": "평소 은행 업무 처리 방법",
  "q": "How do you usually take care of your banking? Describe what you do online and what makes you visit a bank in person.",
  "flow": "모바일 뱅킹(잔액·카드 대금·더치페이) → 자동이체 → 현금은 거의 안 씀 → 지점에 가는 상황(대출·문제) → 정리",
  "tip": "'However, there are still a few situations where…'로 대조를 시작하고 For example로 실제 사례를 드세요. 마지막에 'So overall,…'로 정리하는 습관이 문단 구성력을 보여줍니다.",
  "a": "These days, I take care of almost all my banking on my phone. I use my bank's app to check my balance, pay my credit card bill, and send money to friends, for example when we split the bill after dinner. It only takes a few seconds, and I can do it anytime, even late at night. I've also set up automatic transfers for things like my phone bill and apartment fees, so I don't have to worry about missing a payment. Honestly, I can't remember the last time I used cash. However, there are still a few situations where I have to visit a bank in person. For example, when I applied for a loan to buy my apartment, there was so much paperwork that I had to go to the branch three times. Also, if there's a problem with my account that the app can't solve, I prefer talking to a staff member face to face, because it's easier to explain the situation. So overall, mobile banking is great for simple, everyday things, but for complicated or important matters, I still trust the people at the bank more."
 },
 {
  "id": "q32",
  "source": "predicted",
  "topic": "음악",
  "type": "습관·일상",
  "title": "음악을 듣는 시간과 방법",
  "q": "When and where do you usually listen to music? What do you use to listen, and how do you choose songs for different situations?",
  "flow": "매일 들음 → 출퇴근(아침엔 신나는 곡·퇴근길엔 차분한 곡) → 업무 중 연주곡 → 집에서는 스피커 → 선곡 방법 → 음악의 의미",
  "tip": "상황별(출근·업무·집)로 나누고 각 상황마다 '무엇을 + 왜'를 붙이세요. 'tend to', 'rely on', 'based on my taste'로 습관을 자연스럽게 설명할 수 있습니다.",
  "a": "I listen to music pretty much every day, and what I listen to really depends on the situation. The time I listen the most is during my commute. It takes about an hour by subway, so I always put on my wireless earphones and play a playlist on my phone. In the morning, I choose upbeat K-pop songs, because they help me wake up and get in a good mood before work. On the way home, though, I prefer something calmer, like acoustic songs or R&B, so I can relax after a long day. At work, I sometimes listen to instrumental music when I need to focus, because lyrics tend to distract me. At home, I usually play music through a small Bluetooth speaker in the kitchen while I'm cooking or cleaning. It makes boring chores a lot more fun. As for choosing songs, I mostly rely on playlists that the music app recommends based on my taste, but I also have a few playlists of my own, like one for rainy days. I think music makes even an ordinary day feel a little bit special."
 },
 {
  "id": "q33",
  "source": "predicted",
  "topic": "해외여행",
  "type": "과정·준비",
  "title": "해외여행 준비 과정",
  "q": "What do you usually do to prepare for an overseas trip? Explain the steps you take before leaving home.",
  "flow": "한 달 전부터 준비 → 항공·숙소 예약(리뷰 확인) → 공항에서 숙소 가는 길(실패 경험) → 일정 → 날씨·환전·eSIM → 전날 짐과 여권 확인 → 소감",
  "tip": "과정 설명형은 순서 표현(The first thing, Next, After that, A week before, The night before)이 뼈대입니다. 중간에 짧은 실패 경험('learned that lesson the hard way')을 넣으면 단조로움을 피할 수 있습니다.",
  "a": "I'm kind of a planner, so I usually start preparing for an overseas trip about a month in advance. The first thing I do is book my flight and hotel. I compare prices on a few different websites, and I always read the reviews, especially the bad ones, before I make a reservation. Next, I look up how to get from the airport to the hotel. I learned that lesson the hard way. On my first trip to Japan, I got lost at the airport and wasted almost two hours. After that, I make a rough plan for each day, like which places to visit and which restaurants to try, but I try not to make it too tight. A week before leaving, I check the weather forecast and exchange some money. I also buy an eSIM so I can use my phone as soon as I land. The night before, I pack my bag and double-check the important things, like my passport, my charger, and my travel insurance. It might sound like a lot of work, but preparing well really helps me relax and enjoy the trip."
 },
 {
  "id": "q34",
  "source": "predicted",
  "topic": "지리",
  "type": "장소 묘사",
  "title": "가까운 자연 장소 소개",
  "q": "Describe a natural place near where you live. What can people see there, and why do you like spending time in that place?",
  "flow": "광교호수공원과 광교산 → 호수 풍경(물안개·새) → 산 정상 전망 → 계절별 모습 → 가는 이유 → 가까이 있어 다행이라는 마음",
  "tip": "자연 묘사에는 시각·청각 같은 감각 표현(mist rising, listening to the birds)과 계절별 비교를 넣으세요. 'which isn't very high' 같은 삽입 관계절로 문장을 길게 이어가는 연습을 하세요.",
  "a": "There's a beautiful natural place near my home called Gwanggyo Lake Park, and I also really like the mountain trail near it. The park has two large lakes surrounded by walking paths, trees, and wildflowers. In the early morning, you can see mist rising from the water, and there are ducks and sometimes even herons standing in the shallow parts. If you follow the trail from the park, it leads to Gwanggyo Mountain, which isn't very high, so you can get to the top in about an hour. From there, you can see the whole city. Each season looks completely different. In spring, the cherry blossoms along the lake are amazing. In summer, the trees are thick and green, and in fall, the whole mountain turns red and yellow. I go there whenever I feel stressed or need some fresh air. Just walking under the trees and listening to the birds really clears my head. It's amazing that such a peaceful place exists so close to a busy city, and I feel really lucky to live nearby."
 },
 {
  "id": "q35",
  "source": "predicted",
  "topic": "캠핑",
  "type": "문제 경험",
  "title": "캠핑 중 비가 온 경험",
  "q": "Tell me about a problem you experienced while camping. What happened, how did you solve it, and how did the trip turn out?",
  "flow": "지난가을 가평 → 비 예보가 없어 타프를 안 챙김 → 갑작스러운 폭우 → 텐트로 대피 → 관리인에게 도움 요청 → 다른 캠퍼들과 저녁 → 교훈",
  "tip": "'Big mistake.' 같은 짧은 문장을 섞어 리듬을 주고, 'Within minutes', 'We managed to…', 'Luckily'로 긴박한 전개에서 해결까지 보여 주세요.",
  "a": "Last fall, my wife and I went camping in Gapyeong with a couple of friends. The forecast said it would be cloudy, but there was no mention of rain, so we didn't bring a tarp. Big mistake. Right after we started grilling dinner, it suddenly started pouring. Within minutes, the ground turned muddy, the fire went out, and some of our bags got completely soaked. Everyone was running around trying to save the food and the sleeping bags. We managed to move everything into the tent, but it was too small for four people to eat dinner in. So I ran over to the campsite office and asked the manager if there was anywhere we could go. Luckily, he showed us a covered area with picnic tables that other campers were using too. We finished cooking on a portable gas stove there, and some of the other campers even shared their snacks with us. I was really disappointed at first, but by the end of the night, we were all laughing about it. Since then, I always pack a tarp and waterproof bags, no matter what the forecast says."
 },
 {
  "id": "q36",
  "source": "predicted",
  "topic": "공원",
  "type": "과거 경험",
  "title": "기억에 남는 공원 방문",
  "q": "Tell me about a memorable visit to a park. When did you go, who were you with, and what made that visit special?",
  "flow": "지난봄 아내와 벚꽃 피크닉 → 즉흥적인 결정·빵집 → 벚나무 아래 자리 → 꽃잎 에피소드 → 노을 산책 → 특별했던 이유",
  "tip": "극적인 사건이 없어도 감각적인 디테일(petals fell like snow)과 '왜 특별했는지'를 설명하면 충분히 AL 수준의 답변이 됩니다. 'on the spur of the moment', 'at their peak'를 활용해 보세요.",
  "a": "One of my favorite park memories is from last spring, when my wife and I had a picnic at Gwanggyo Lake Park. It was the first really warm weekend of the year, and the cherry blossoms were at their peak, so we decided to go on the spur of the moment. We stopped by a bakery on the way and bought some sandwiches, strawberries, and two iced coffees. When we got to the park, it was pretty crowded, but we found a nice spot under a big cherry tree near the lake. We spread out our blanket and spent the whole afternoon there, eating, talking, and taking pictures. Every time the wind blew, the petals fell like snow, and I remember my wife laughing because some landed in her coffee. Later, as the sun started to go down, we walked around the lake and watched the sky turn orange and pink. Nothing dramatic happened that day, but that's actually what made it special. We weren't in a hurry, we didn't check our phones, and we just enjoyed being together. Whenever I see cherry blossoms now, I think of that day."
 },
 {
  "id": "q37",
  "source": "predicted",
  "topic": "커피숍",
  "type": "과거·현재 비교",
  "title": "예전과 지금의 카페 이용 비교",
  "q": "Compare the way you used coffee shops in the past with the way you use them now. What has changed, and why?",
  "flow": "대학생 때는 공부 장소 → 직장 초반에는 테이크아웃 → 지금은 휴식 공간(인테리어·드립커피) → 삶의 변화와 연결",
  "tip": "단순한 2단계 비교보다 3단계(대학 → 직장 초반 → 지금)로 나누면 길이와 깊이가 늘어납니다. 마지막 비유(a gas station for caffeine)처럼 창의적인 정리 문장은 인상적인 마무리가 됩니다.",
  "a": "The way I use coffee shops has changed quite a bit over the years. When I was in college, cafes were mainly a place to study. I'd go there with a heavy backpack, order the cheapest drink, and stay for hours working on assignments, because my dorm was too noisy. After I started working, I didn't have much time, so I usually just grabbed a coffee to go on my way to the office. All I cared about was how fast and cheap it was. These days, I've gone back to staying at cafes, but for a different reason. Now it's more about relaxing. On weekends, I look for cafes with comfortable seats, nice interiors, and a quiet atmosphere, and I'll happily drive thirty minutes to visit a nice one outside the city. I also care more about the quality of the coffee now, so I sometimes try hand-drip coffee instead of my usual iced Americano. I think the change reflects my life. When I was younger, a cafe was a study room, then it was a gas station for caffeine, and now it's more like a place to rest and recharge."
 },
 {
  "id": "q38",
  "source": "predicted",
  "topic": "집",
  "type": "습관·일상",
  "title": "집에서 보내는 평소 저녁",
  "q": "What do you usually do at home on a weekday evening? Describe your routine from the time you arrive home until you go to bed.",
  "flow": "7시 귀가·옷 갈아입기 → 아내와 저녁 준비 → 설거지 분담 → 드라마·독서 → 헬스장 → 다음 날 준비 → 솔직한 마무리(휴대폰)",
  "tip": "일과 설명은 시간 표현(around seven, around eight-thirty, Before going to bed)으로 흐름을 잡으세요. 마지막의 'to be honest, I often end up…' 같은 솔직한 한마디가 자연스러움을 더합니다.",
  "a": "My weekday evenings are pretty routine. I usually get home around seven. The first thing I do is change into comfortable clothes and wash up, because it helps me switch from work mode to home mode. Then my wife and I make dinner together. We don't cook anything fancy on weekdays, usually just rice, soup, and a couple of side dishes, or sometimes we order delivery when we're too tired. After dinner, I do the dishes while my wife cleans up the rest of the kitchen. Around eight-thirty, we finally get some free time. We usually watch an episode or two of a TV series together, or I go into my study and read for a while. Two or three times a week, I also go to the gym in our apartment complex for about forty minutes. Before going to bed, I take a shower, check my schedule for the next day, and lay out my clothes, which saves me a lot of time in the morning. I try to be in bed by midnight, but to be honest, I often end up scrolling on my phone longer than I should."
 },
 {
  "id": "q39",
  "source": "predicted",
  "topic": "집",
  "type": "문제 경험",
  "title": "집에서 생긴 문제 해결",
  "q": "Describe a problem you had at home. What was the problem, what did you do to fix it, and what happened in the end?",
  "flow": "저녁 준비 중 바닥에 물 → 싱크대 배관 누수 발견 → 밸브 잠그기·임시 조치 → 관리실 연락 → 불편한 밤 → 다음 날 수리 → 교훈",
  "tip": "'sure enough', 'That meant…', 'just in case' 같은 연결 표현으로 원인과 결과를 이어가세요. 해결 과정을 단계별로(밸브 → 양동이 → 전화) 말하면 훨씬 구체적으로 들립니다.",
  "a": "A few months ago, I had a pretty annoying problem at home. I was making dinner one evening when I noticed that my socks were wet. I looked down and saw water on the kitchen floor. At first, I thought I had just spilled something, so I wiped it up, but a few minutes later, it was wet again. So I opened the cabinet under the sink, and sure enough, water was dripping from one of the pipes. I quickly turned off the water valve and put a bucket and some towels under the pipe. Then I called the building management office, but since it was already after eight, they told me a repair person couldn't come until the next morning. That meant we couldn't use the kitchen sink, so we had to wash the dishes in the bathroom, which was really inconvenient. The next morning, a repair worker came and found that a connection had come loose. He fixed it in about ten minutes. I was so relieved it wasn't a bigger problem, because water damage can get really expensive. Now I check under the sink once in a while, just in case."
 },
 {
  "id": "q40",
  "source": "predicted",
  "topic": "롤플레이",
  "type": "질문하기",
  "title": "캠핑장 예약 문의",
  "q": "You want to book a campsite for next weekend. Call the campsite office and ask three or four questions to get the information you need.",
  "flow": "전화한 목적 → 빈자리·강가 자리 → 요금·전기 포함 여부 → 텐트 대여 → 체크인·체크아웃 → 모닥불 → 감사",
  "tip": "질문마다 이유를 덧붙이세요(전기 히터를 가져감 → 전기 요금 포함?). 'I was wondering if…', 'If so,…', 'Oh, and one more thing'은 공손하고 자연스러운 롤플레이 표현입니다.",
  "a": "Hi, I'm calling about a reservation. My friend and I are planning a camping trip next weekend, and I found your campsite online. It looks great, but I have a few questions before I book. First of all, do you have any sites available for two people on Saturday night? We'd prefer a spot near the river, if possible. Second, how much does it cost per night? And does that price include electricity, or is that extra? We're bringing a small electric heater, because it might get cold at night. Third, we don't have our own tent, so I was wondering if we could rent one there. If so, how much is it, and do we need to reserve it in advance? Also, what time are check-in and check-out? We'll probably arrive around noon, so I'd like to know if we can set up early. Oh, and one more thing. Are campfires allowed, or is that not permitted? Okay, that's all for now. Thank you so much for your help. I'll talk to my friend and then book the site on your website."
 },
 {
  "id": "q41",
  "source": "predicted",
  "topic": "롤플레이",
  "type": "문제 해결",
  "title": "캠핑 예약 일정 변경",
  "q": "You booked a campsite, but your car has broken down and you cannot go. Call the office, explain the problem, and suggest two or three alternatives.",
  "flow": "이름·예약 확인 → 사정(차 고장·대중교통으로 갈 수 없음) → 사과 → 대안 1 날짜 변경 → 대안 2 환불(규정 언급) → 대안 3 양도 → 감사",
  "tip": "대안마다 '왜 가능한지' 근거를 대면(규정상 3일 전 통보) 설득력이 생깁니다. 'Would it be possible to…?', 'If neither of those works…'는 협상형 롤플레이의 필수 표현입니다.",
  "a": "Hi, my name is Harry Kim, and I have a reservation for this Saturday for two people. I'm calling because, unfortunately, something came up. My car broke down this morning on my way to work, and the repair shop said it won't be ready until next Tuesday. Your campsite is pretty far from public transportation, so there's no way for us to get there without a car. I'm really sorry about the short notice. I'd like to ask about a few options. First, would it be possible to move my reservation to next weekend? We'd be happy to take any site that's available. Second, if that doesn't work, could I cancel the reservation and get a refund? I know your policy says you need three days' notice, and I'm calling exactly three days before, so I hope that's okay. Or, if neither of those works, could I transfer the reservation to a friend? He's been wanting to go camping, and he could use the site instead. Please let me know which option is possible. Again, sorry for the trouble, and thank you for understanding."
 },
 {
  "id": "q42",
  "source": "predicted",
  "topic": "롤플레이",
  "type": "질문하기",
  "title": "호텔 예약 문의",
  "q": "You are planning a trip and need a hotel room. Call a hotel and ask three or four questions before making a reservation.",
  "flow": "인사·여행 목적 → 트윈룸 가능 여부 → 가격·직접 예약 할인 → 조식 → 역에서 오는 교통편 → 얼리 체크인 → 감사",
  "tip": "구체적인 숫자(날짜·시간)를 넣으면 실감 나는 롤플레이가 됩니다. 'Oh, and I almost forgot,…'으로 질문을 하나 더하면 즉흥적인 대화처럼 들립니다.",
  "a": "Hi, good afternoon. I'm planning a trip to Busan next month, and I'm interested in staying at your hotel. Before I make a reservation, could I ask you a few questions? First, do you have a twin room available for two people from the fifteenth to the seventeenth? I'm traveling with a friend, so we'd prefer two separate beds. Second, how much is the room per night, and is there a discount if we book directly instead of through a travel website? Third, is breakfast included in the price? If not, how much is it, and what kind of food do you serve? And lastly, what's the best way to get to the hotel from Busan Station? We won't have a car, so I'd like to know if there's a shuttle bus or if we should take a taxi. Oh, and I almost forgot. Is it possible to check in a little early? Our train arrives around eleven in the morning. Okay, I think that's everything. Thank you for your help. I'll talk to my friend and call you back to confirm the reservation."
 },
 {
  "id": "q43",
  "source": "predicted",
  "topic": "롤플레이",
  "type": "문제 해결",
  "title": "호텔 예약 내용이 다른 상황",
  "q": "You arrive at a hotel, but the room is different from what you booked. Explain the problem to the front desk and suggest two or three ways to solve it.",
  "flow": "방 번호·문제 설명 → 예약 증거(확인 메일) → 이유 → 대안 1 객실 변경 → 대안 2 추가 침대 → 대안 3 내일 이동 + 할인 → 요청",
  "tip": "불만 상황에서도 정중함을 유지하세요: 'I think there's been a mix-up', 'I understand mistakes happen'. 'In that case, I think … would be fair'처럼 조건부 요청을 덧붙이면 고급 협상 표현이 됩니다.",
  "a": "Hi, excuse me. I just checked in to room 1205, and I think there's been a mix-up with my reservation. I booked a twin room with two separate beds, and I have the confirmation email right here on my phone. But the room I was given only has one double bed. I'm traveling with a friend, so sharing a bed really isn't an option for us. I understand mistakes happen, so I'd just like to find a solution. First, could you move us to a twin room, if one is available tonight? We don't mind if it's on a different floor. If there aren't any twin rooms left, would it be possible to bring an extra bed into this room? And if neither of those is possible, maybe we could stay in this room tonight and move to a twin room tomorrow morning. In that case, I think a discount for tonight would be fair. Could you please check what you can do for us? We're pretty tired from the trip, so we'd really appreciate it if this could be sorted out quickly. Thank you."
 },
 {
  "id": "q44",
  "source": "predicted",
  "topic": "롤플레이",
  "type": "질문하기",
  "title": "친구에게 새 카페 질문",
  "q": "Your friend recently visited a new coffee shop. Ask your friend three or four questions about the place before you visit it yourself.",
  "flow": "SNS로 알게 됨 → 위치·교통·주차 → 추천 메뉴·커피 맛 → 덜 붐비는 시간 → 노트북 작업 가능 여부 → 같이 가자는 제안",
  "tip": "친구에게 하는 롤플레이는 감탄사와 구어체(such a pain, My treat!)로 친근함을 살리세요. 'A or B?' 형태로 묻거나 꼬리 질문을 붙이면 대화가 풍부해집니다.",
  "a": "Hey, Jisoo! I saw your Instagram post about that new cafe downtown. The pictures looked amazing! I've been wanting to go there, so can I ask you a few things about it? First, where exactly is it? Is it close to the subway station, or would it be better to drive? And if I drive, is there a place to park nearby? Parking downtown is always such a pain. Second, what did you order? Everyone's posting about the cake, but I'm more curious about the coffee. Was it actually good, or is the place just popular because it looks nice? Third, when is it usually less crowded? I want to bring a book and sit there for a couple of hours, so I'd like to avoid the busiest times, like weekend afternoons. Oh, and is it a good place to work on a laptop? Are there power outlets at the tables? Thanks so much. Actually, if you don't mind going again, maybe we could go together this weekend. My treat!"
 },
 {
  "id": "q45",
  "source": "predicted",
  "topic": "롤플레이",
  "type": "문제 해결",
  "title": "카페 약속을 지키기 어려운 상황",
  "q": "You planned to meet a friend at a coffee shop, but you have to work late. Call your friend, explain the situation, and suggest three alternatives.",
  "flow": "사과 → 이유(마감이 앞당겨짐) → 미안한 마음 → 대안 1 9시에 만나기 → 대안 2 내일 → 대안 3 영상 통화 후 주말 → 보상 → 선택 요청",
  "tip": "이유를 구체적으로(마감이 앞당겨짐, moved up a deadline) 말하고 보상 제안('to make it up to you, … is on me')을 덧붙이면 대안 제시가 더 완성도 있게 들립니다.",
  "a": "Hey, Jisoo, it's me. I'm really sorry to call you so last minute, but I don't think I can make it to the cafe at seven tonight. My manager just told me that an important client moved up a deadline, so my whole team has to stay late to finish a report. I tried to get out of it, but I really can't. I feel terrible, because I know you've been looking forward to trying that cafe. So I have a few ideas. First, I think I can finish by around nine. If it's not too late for you, we could still meet, and I'd come straight to the cafe. Second, if nine is too late, how about meeting tomorrow after work instead? I'll make sure to leave on time. Third, if you're busy tomorrow too, let's just do a quick video call tonight to catch up, and then meet properly this weekend. And to make it up to you, the coffee and cake are on me, whichever option you choose. Just text me which one works for you. Again, I'm so sorry for changing our plans."
 },
 {
  "id": "q46",
  "source": "predicted",
  "topic": "날씨",
  "type": "묘사·선호",
  "title": "좋아하는 계절과 날씨",
  "q": "What is your favorite season? Describe the weather during that season and explain what you like to do then.",
  "flow": "가을을 좋아함 → 날씨(기온·습도·하늘) → 활동 1 캠핑 → 활동 2 단풍 등산 → 활동 3 산책 → 아쉬움(너무 짧음) → I wish",
  "tip": "날씨 묘사에 구체적인 수치(around twenty degrees)와 비교(after the hot, sticky summer)를 넣고, 'I wish it lasted longer'(가정법)로 마무리하면 AL 수준의 문법을 자연스럽게 보여줄 수 있습니다.",
  "a": "My favorite season is definitely fall. In Korea, fall usually runs from late September to early November, and the weather is just perfect. During the day, it's sunny and around twenty degrees, and in the morning and evening, it gets a little chilly, so you can wear a light jacket. Most importantly, it's not humid at all, which is a huge relief after the hot, sticky summer. The sky is also really clear and blue, which is why people in Korea say the sky gets higher in the fall. There are so many things I like to do in fall. First, it's the best season for camping, since there are no mosquitoes and sitting by a campfire feels really cozy. I also love going hiking to see the autumn leaves. When the mountains turn red and yellow, the view is absolutely stunning. And on weekends, I like taking long walks around the lake park with my wife. The only problem is that fall is way too short. It feels like it's gone in just a few weeks, and suddenly it's freezing cold. I wish it lasted longer."
 },
 {
  "id": "q47",
  "source": "predicted",
  "topic": "날씨",
  "type": "습관·일상",
  "title": "날씨에 따라 달라지는 활동",
  "q": "How does the weather affect your daily activities? Explain what you usually do on sunny days and on rainy days.",
  "flow": "매일 날씨 확인 → 맑은 날(한 정거장 걷기·산책·캠핑) → 비 오는 날(택시·집에서 쉬기) → 미세먼지",
  "tip": "'a totally different story'로 대조를 전환하고, 마지막에 한국 특유의 이슈(미세먼지)를 더하면 질문 범위를 넘어 답변을 확장하는 능력을 보여줄 수 있습니다.",
  "a": "The weather has a pretty big effect on my daily life. The first thing I do every morning is check the weather app, because it helps me decide what to wear and how to get to work. On sunny days, I feel a lot more energetic. If the weather's nice, I sometimes get off the subway one stop early and walk the rest of the way to the office. After work, I might go for a walk around the lake park or meet a friend at a cafe with a terrace. On weekends, sunny days are perfect for camping or a picnic. Rainy days are a totally different story. I usually take a bus or a taxi instead of walking, because I hate getting my shoes wet. After work, I just go straight home. I like staying in, making some hot noodles, and watching a movie while listening to the rain. Actually, I don't mind rainy weekends that much, because they give me an excuse to be lazy. One thing I do worry about is fine dust. On days when the air quality is bad, I try not to go outside at all, and when I have to, I wear a mask."
 },
 {
  "id": "q48",
  "source": "predicted",
  "topic": "날씨",
  "type": "문제 경험",
  "title": "갑작스러운 비로 바뀐 계획",
  "q": "Tell me about a time when bad weather changed your plans. What were you going to do, what happened, and what did you do instead?",
  "flow": "한강 피크닉 계획 → 맑다는 예보·준비 → 갑자기 소나기 → 편의점으로 피신 → 흠뻑 젖고 웃음 → 카페로 이동 → 좋은 추억",
  "tip": "날씨 변화를 'the sky suddenly got dark'처럼 장면으로 묘사하고, 'By the time…', 'ended up -ing'로 결과를 이어가세요. 결말에서 감정이 반전되는 모습을 표현하면 이야기가 완성됩니다.",
  "a": "Last summer, a friend and I planned a picnic at Hangang Park. We'd been talking about it for weeks, and the forecast said it would be sunny all day. So we packed sandwiches, fruit, a portable speaker, and a big blanket. When we got to the park around noon, it was really hot, but the sky was clear, so we found a spot under a tree and set everything up. But about thirty minutes later, the sky suddenly got dark, and it started pouring. It was one of those sudden summer showers. We didn't have umbrellas, so we just grabbed our stuff and ran to a convenience store nearby. By the time we got there, we were soaking wet, and our sandwiches were completely ruined. We stood there laughing at how ridiculous we looked. Since the rain didn't look like it would stop, we decided to go to a cafe across the street. We ordered hot drinks, dried off a little, and ended up talking for hours. It wasn't the day we'd planned, but honestly, it's one of my favorite memories with that friend."
 },
 {
  "id": "q49",
  "source": "predicted",
  "topic": "교통",
  "type": "습관·일상",
  "title": "평소 이동 수단",
  "q": "What kinds of transportation do you usually use? Explain how you travel around your city and why you choose those methods.",
  "flow": "지하철이 1순위 → 통근(수원에서 서울)·운전과 비교 → 지하철의 장점 → 버스 환승 할인 → 주말에는 운전 → 택시 → 정리",
  "tip": "교통수단별(지하철·버스·차·택시)로 '언제 + 왜'를 말하세요. 한국 교통의 특징(무료 환승)을 설명하면 정보 전달력을 보여줄 수 있습니다.",
  "a": "I mostly use public transportation, and the subway is definitely my first choice. I live in Suwon and work in Seoul, so my commute is about an hour each way. Driving would take even longer because of the traffic, and parking near my office is really expensive. On the subway, I don't have to worry about any of that. I can listen to music, read the news, or even take a quick nap if I get a seat. The subway system here is also super convenient. It's clean and fast, and the trains come every few minutes. When my destination isn't close to a station, I take a bus, and in Korea, you can transfer between the subway and buses for free within thirty minutes, which saves a lot of money. On weekends, though, I usually drive. When my wife and I go camping or grocery shopping, we have a lot to carry, so a car is much more practical. And once in a while, when I'm running late, I take a taxi, but I try not to, because it's pretty expensive. Overall, public transportation fits my lifestyle really well."
 },
 {
  "id": "q50",
  "source": "predicted",
  "topic": "교통",
  "type": "과거·현재 비교",
  "title": "예전과 지금의 길 찾기 비교",
  "q": "How has the way you find your route changed over time? Compare how you got directions in the past with how you do it now.",
  "flow": "10대 때 지도 출력·전화·길 묻기 → 버스를 잘못 탄 경험 → 지금은 앱(실시간·빠른 출구) → 편리함 → 의존에 대한 비판 → 보조 배터리",
  "tip": "과거 습관 'I'd(would) + 동사'와 짧은 일화를 함께 쓰세요. 'That said,…'로 현재 방식의 단점까지 언급하면 비교 질문에서 깊이 있는 답변이 됩니다.",
  "a": "The way I find my way around has completely changed. When I was a teenager, there were no smartphones, so if I had to go somewhere new, I'd look it up on a map website on my computer and write down the directions, or even print out the map. Sometimes I'd call the place and ask them how to get there. If I got lost, the only option was to ask people on the street. I remember once taking the wrong bus and ending up on the other side of the city. It took me two hours to get home. Nowadays, I just open a map app on my phone. It tells me exactly which bus or subway to take, when it's arriving, and even which subway car is closest to the exit. It also shows real-time traffic, so I can choose the fastest route. It's incredibly convenient, and I almost never get lost anymore. That said, I think I've become too dependent on it. I don't really remember routes anymore, and when my battery is low, I get nervous. So these days, I try to carry a portable charger with me, just in case."
 },
 {
  "id": "q51",
  "source": "predicted",
  "topic": "교통",
  "type": "문제 경험",
  "title": "대중교통에서 물건을 잊은 경험",
  "q": "Tell me about a problem you had while using public transportation. What happened, how did you deal with it, and what was the result?",
  "flow": "퇴근 버스에서 잠듦 → 급하게 내림 → 지갑 분실 발견 → 버스 회사 연락 → 기사님이 찾아 줌 → 다음 날 찾아오며 감사 → 교훈",
  "tip": "'My heart sank', 'I figured it must have…'(과거 추측) 같은 감정·추론 표현이 이야기에 깊이를 줍니다. 결말에 행동 변화(Since then…)를 넣는 습관을 들이세요.",
  "a": "Last month, I had a pretty stressful experience on the bus. I was heading home after a long day, and I was so tired that I fell asleep. When I woke up, I realized I was almost at my stop, so I jumped up and rushed off the bus. A few minutes later, I reached into my pocket and realized my wallet wasn't there. My heart sank, because it had my ID, my credit cards, and some cash in it. I figured it must have fallen out while I was sleeping. Luckily, I remembered the bus number, so I looked up the bus company's phone number and called them right away. I explained what time I got off, which stop it was, and what my wallet looked like. The staff told me they would contact the driver and call me back. About an hour later, they called and said the driver had found it under the seat. I was so relieved. The next morning, I went to the bus depot to pick it up, and I even brought some coffee for the driver to say thanks. Since then, I always check my seat before I get off."
 },
 {
  "id": "q52",
  "source": "predicted",
  "topic": "재활용",
  "type": "습관·과정",
  "title": "집에서 분리배출하는 방법",
  "q": "How do you handle recycling at home? Describe the steps you follow and the different kinds of things you separate.",
  "flow": "한국은 분리배출이 엄격함 → 집 안 분류(통 4개·종량제 봉투) → 헹구기·라벨 제거·상자 펴기 → 주 1회 배출 → 투명 페트병 별도 → 소감",
  "tip": "과정 설명과 한국 고유 제도(종량제 봉투, 투명 페트병 분리)를 영어로 풀어 설명하는 연습을 하세요. 수동태(is taken seriously, can't be recycled)를 적절히 섞으면 문법 다양성이 올라갑니다.",
  "a": "In Korea, recycling is taken really seriously, and every apartment complex has its own rules, so I'm pretty careful about it. At home, we have four separate bins in the utility room: one for plastic, one for paper, one for cans and glass, and one for food waste. We also use special bags for general garbage, which you have to buy. Whenever I finish something like a yogurt cup or a delivery container, I rinse it out first, because if it's dirty, it can't actually be recycled. I also peel the labels off plastic bottles and crush them so they take up less space. For cardboard boxes, I remove the tape and flatten them. Once a week, usually on Wednesday evening, my wife and I take everything down to the recycling area in our apartment complex. There, everything is sorted even more carefully. For example, clear plastic bottles go in a different bin from other plastics. Honestly, it can be a bit of a hassle, but it's become a habit now, and it feels good to know I'm doing my part for the environment."
 },
 {
  "id": "q53",
  "source": "predicted",
  "topic": "재활용",
  "type": "과거·현재 비교",
  "title": "예전과 지금의 재활용 습관",
  "q": "How have your recycling habits changed since you were younger? Explain what you did before and what you do differently now.",
  "flow": "어릴 때는 엄마 담당 → 대학 기숙사 시절 무관심 → 자취 후 경비원에게 지적받은 일 → 지금은 철저히 분리 → 쓰레기 줄이기 → 평가",
  "tip": "변화의 '계기'(경비원이 찾아온 일)를 구체적인 일화로 넣으면 비교 답변이 훨씬 설득력 있어집니다. 'Things changed when…', 'compared to before'로 시기를 전환하세요.",
  "a": "My recycling habits have changed a lot since I was younger. When I was a kid, my mom took care of all the recycling, so I honestly didn't think about it at all. I'd just leave empty bottles or snack wrappers on the kitchen table, and somehow they disappeared. Even in college, when I lived in a dorm, I wasn't very careful. I'd often throw everything into one trash can because I was too lazy to separate things. Things changed when I started living on my own. My apartment building had strict recycling rules, and once, the security guard actually knocked on my door because I hadn't separated my trash properly. It was so embarrassing. After that, I started paying a lot more attention. Now I rinse every container, take the labels off bottles, and separate everything carefully. I've also tried to reduce waste in the first place. I bring my own tumbler to cafes and use reusable shopping bags. I'm definitely not perfect, but compared to before, I'm much more aware of how much waste I produce, and I think that's a good change."
 },
 {
  "id": "q54",
  "source": "predicted",
  "topic": "재활용",
  "type": "문제 경험",
  "title": "분리배출 방법을 몰랐던 경험",
  "q": "Describe a time when you were unsure how to recycle something. What confused you, how did you find out what to do, and what did you learn?",
  "flow": "배달 용기 종류 → 소스 묻은 플라스틱·스티로폼에 대한 혼란 → 인터넷 검색 실패 → 공지문 확인 → 경비원에게 질문 → 배운 점 → 이후 습관",
  "tip": "'whether it still counted if…', 'were supposed to go' 같은 간접 의문·조건 표현으로 혼란을 묘사하고, 해결 단계(검색 → 공지 → 질문)를 순서대로 설명하세요.",
  "a": "A few weeks ago, I ordered some food for dinner, and it came in a bunch of different containers. There was a plastic bowl covered in red sauce, a paper bag, a foam box, and some disposable chopsticks. After eating, I stood in the kitchen not knowing what to do. I knew plastic should be recycled, but I wasn't sure whether it still counted if it had sauce stains that wouldn't wash off. I also had no idea where the foam box and the chopsticks were supposed to go. So first, I searched online, but I found different answers on different websites, which made me even more confused. Then I remembered there was a notice in our building's recycling area, so I went down and read it. It said that plastic with stains that won't come off should go in the general garbage. I still wasn't sure about the foam box, so I asked the security guard, and he kindly explained that clean foam can be recycled, but not if it's dirty. It took a little extra time, but I learned a lot. Now I try to choose restaurants that use less packaging."
 },
 {
  "id": "q55",
  "source": "predicted",
  "topic": "스마트폰",
  "type": "묘사·일상",
  "title": "자주 사용하는 스마트폰 기능",
  "q": "Tell me about the smartphone apps or features you use most often. What do you use them for, and which one is especially useful to you?",
  "flow": "자주 쓰는 앱 3개 → 메신저(단체방) → 음악 → 가장 유용한 지도(기능 상세) → 카메라 → 의존에 대한 생각",
  "tip": "'If I had to pick,…'(가정법)으로 시작해 여러 기능을 소개하고, '가장 유용한 것' 하나를 깊이 있게 설명하세요. 'I'd be lost without it, literally' 같은 말장난도 자연스러운 표현입니다.",
  "a": "I use my smartphone for almost everything, but if I had to pick, the apps I use most are a messaging app, my music app, and a map app. Messaging is probably the one I use the most. I'm in a lot of group chats with my family, my friends, and my coworkers, so I'm checking messages all day. My music app is also always on, especially during my commute. But the one I find the most useful is definitely the map app. I'm terrible with directions, so I'd be lost without it, literally. It shows me the fastest route, tells me exactly when the next bus is coming, and even recommends nearby restaurants with reviews. When I'm going somewhere new, I check it before leaving so I know how long it'll take. I also use the camera a lot. Whenever I go camping or to the park with my wife, I take tons of pictures, and the phone automatically organizes them into albums, which is really handy. Honestly, I sometimes worry that I depend on my phone too much, but at the same time, it makes my daily life so much easier."
 },
 {
  "id": "q56",
  "source": "predicted",
  "topic": "스마트폰",
  "type": "문제 경험",
  "title": "스마트폰 없이 길을 찾은 경험",
  "q": "Tell me about a time when you could not use your smartphone when you needed it. What happened, what did you do, and how did the situation end?",
  "flow": "1년 전 낯선 동네에서 저녁 약속 → 지도를 보다가 배터리 방전 → 식당 이름도 모름 → 카페 직원에게 도움 요청 → 냅킨에 그린 지도 → 20분 뒤 도착 → 보조 배터리 습관",
  "tip": "'halfway there', 'I'd never been to before'(과거완료), 'At first, I panicked… Then I decided…'로 감정에서 행동으로의 전환을 보여주세요. 작은 디테일(냅킨에 그린 지도)이 이야기를 생생하게 만듭니다.",
  "a": "About a year ago, I was meeting some friends for dinner at a restaurant in a neighborhood I'd never been to before. I was using the map app to find it, but my battery was already low, and halfway there, my phone suddenly died. I had no idea where I was, and I couldn't call my friends to tell them I'd be late. I didn't even remember the exact name of the restaurant. I just knew it was an Italian place near a church. At first, I panicked a little. Then I decided to go into a cafe and ask for help. I explained my situation to the staff, and one of them was really kind. She asked her coworkers if they knew an Italian restaurant near a church, and one of them knew exactly where it was. She even drew me a little map on a napkin. I followed it and finally found the restaurant about twenty minutes later. My friends were worried because they couldn't reach me, but we laughed about it over dinner. After that, I bought a portable charger, and now I never leave home without it."
 }
];
